server:
  port: 80
  servlet:
    context-path: /

# mybatis_config
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.cm.product.entity
  configuration:
    map-underscore-to-camel-case: true

#datasource
spring:
  datasource:
    url: jdbc:mysql://:3306/test?useUnicode=true&characterEncoding=UTF-8
    username:
    password:
  redis:
    timeout: 5000
    cluster:
      nodes:
  rabbitmq:
    addresses:
    port: 5672
    username: guest
    password: guest
logging:
  level:
    com.cmc: debug


